name: pr-verification

on:
  pull_request:
    types:
      - opened


jobs: 
  pr-run:
    runs-on: ubuntu-latest
    steps:
        - name: getting pr 
          run: |
            echo ${{ github.event.pull_request.head.sha }}
            echo ${{ github.head_ref }} === revision
            echo ${{ github.event.pull_request.head.repo.full_name }} | cut -d/ -f2 
            echo "REPO_NAME=$(echo ${{ github.event.pull_request.head.repo.full_name }} | cut -d/ -f2)" >> $GITHUB_ENV
            
            echo PRrepo==${{ github.event.pull_request.head.repo.full_name }}
            echo ORrepo==${{ github.repository }}
        - name: checkout manifest repo
          uses: actions/checkout@v3
          with:
            repository: 'amalx-ssrc/tii_sel4_manifest'
            ref: 'tii/development'
            path: 'tii_sel4_manifest'
        - name: checkout sel4repo
          uses: actions/checkout@v3
          with:
            path: sel4repo

        - name: view all
          run: |
            ls
            ls sel4repo 
            ls tii_sel4_manifest
            pwd
            echo $REPO_NAME

        - name: PR from same repository 
          if:  github.event.pull_request.head.repo.full_name == github.repository
          run: |
            echo same repo
            ${{ github.head_ref }}
        - name: PR from forked repository
          if: github.event.pull_request.head.repo.full_name != github.repository 
          run: |
            echo $REPO_NAME
            export REPO_NAME=camkes-tool
            sed -i "/$REPO_NAME.git/c\<extend-project name=\"$REPO_NAME.git\"                remote=\"tiiuae\" revision=\"${{ github.head_ref }}\"/>" ./tii_sel4_manifest/external.xml
            cat tii_sel4_manifest/external.xml
